#!/bin/bash

echo -e "\e[31;49;1;4mMY SCRIPTS HELP:\e[0m"
echo -e "\e[33;1maddsrc.sh:\e[0m Display the files that need to be added in the Makefile"
echo -e "\e[33;1mcount_files.sh:\e[0m Display the number of files in this folder"
echo -e "\e[33;1mdo-op \e[33;4m[number]\e[0m \e[33;1;4m[operator]\e[0m \e[33;1;4m[number]\e[0m\e[33;1m:\e[0m Display the result of the operation"
echo -e "\e[33;1mfind_sh.sh:\e[0m Display all the .sh files"
echo -e "\e[33;1mhelp.sh:\e[0m Display all the command of my_scripts"
echo -e "\e[33;1minfo_file \e[33;4m[file]\e[0m\e[33;1m:\e[0m Display the file informations"
echo -e "\e[33;1mmake_that.sh:\e[0m Make .c files with gcc and run the output"
echo -e "\e[33;1mmkproject.sh \e\e[33;4m[github-repo-link]\e[0m \e[33;1;4m[semester-number]\e[0m \e[33;1;4m[module-name]\e[0m \e[33;1;4m[project-folder-name]\e[0m \e[33;1;4m[executable-name]\e[0m \e[33;1;4m[library1 library2 ...]\e[0m\e[33;1m:\e[0m Create a C project structure"
echo -e "\e[33;1mmr_clean.sh:\e[0m Delete all the temporary files"
echo -e "\e[33;1mmy_cat \e[33;4m[files]\e[0m\e[33;1m:\e[0m Display the files content"
echo -e "\e[33;1mpush_that.sh \e[33;4m[message]\e[0m\e[33;1m:\e[0m Push all the files in the repositorie"
echo -e "\e[33;1mstyle_that.sh:\e[0m Execute the coding-style-checker in the folder and display the errors"
echo -e "\e[33;1mupdate_lib.sh \e[33;4m[lib1 lib2 ...]\e[0m\e[33;1m:\e[0m Update the libs in a C project"
