##
## EPITECH PROJECT, 2023
## starting with makefile
## File description:
## starting with makefile
##

SRC	=	flag_c.c			\
		flag_s.c			\
		flag_d.c			\
		flag_i.c			\
		flag_p.c			\
		flag_o.c			\
		flag_u.c			\
		flag_x.c			\
		flag_bigx.c			\
                flag_e.c          		\
                flag_bige.c			\
                flag_f.c			\
		flag_bigf.c			\
                flag_g.c          		\
                flag_bigg.c			\
                flag_a.c			\
		flag_biga.c			\
                flag_n.c          		\
                flag_m.c          		\
		flag_b.c			\
		flag_bigs.c			\
		flag_bigd.c			\
		flag_percent.c			\
		find_format.c 			\
		get_format.c			\
		my_show_formating.c 		\
		sub_format_double.c		\
		format_it_double.c		\
		precise_it_double.c		\
		sub_format_int.c		\
		format_it_int.c			\
		precise_it_int.c		\
		format_it_char.c		\
		sub_format_char.c		\
		format_it_str.c			\
		sub_format_str.c		\
		specifier_int.c			\
		specifier_base.c		\

OBJ	=	$(SRC:.c=.o)

NAME = my_flags

all:  $(NAME)

$(NAME): $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re:	fclean all
