name: [project-name]

on: [push, pull_request]

env:
  MIRROR_URL: [git]
  EXECUTABLE: [project-exec]

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Launch coding style checker
        run: check.sh $(pwd) $(pwd)
      - name: Check coding style
        run:
          cat coding-style-reports.log;
          .github/workflows/display_coding_style

  check_program:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Launch "make"
        run: make
        timeout-minutes: 2
      - name: Launch "make clean"
        run: make clean
      - name: Check program compilation
        run: .github/workflows/check_program_compilation ${{ env.EXECUTABLE }}
      - name: Check banned functions
        run: .github/workflows/check_banned_functions [project-exec] .github/workflows/authorized_functions.txt
      - name: Launch "make tests_run"
        run: make tests_run
        timeout-minutes: 2
      - name: Check repository size
        run: |
          make fclean
          size=$(du -sm --exclude='.git' | cut -f1)
          limit=50
          if [ "$size" -gt "$limit" ]; then
            echo "::error title=Repository size::Repository size is too big ($size MB > $limit MB)"
            exit 1
          else
            echo "::notice title=Repository size::Repository size is correct ($size MB <= $limit MB)"
            exit 0
          fi

  push_to_mirror:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/heads/ga-ignore-') == false &&
      github.repository != '[git-ref]'
    needs: check_program
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
